### ISSUE TITLE
Bug: ReferenceError: process is not defined 

### ISSUE THREAD

**Issue by gtopalbalance** [coinbase/coinbase-wallet-sdk#967] opened 2023-08-07 09:20 UTC
### Describe the bug

Remixjs & Wagmi - process.env undefined error on CoinbaseWalletSDK.js

### Steps

1. Create an remixjs project and add wagmi package
2. Add @coinbase/wallet-sdk package to project
3. Open browser with "Inspect Console" tool
4. Connect wallet button with wagmi
5. Select any network
6. Click "Coinbase Wallet" button
7. See error browser console screen.
8. Click details after go CoinbaseWalletSDK.js file line 13 and 14.

<img width="522" alt="image" src="https://github.com/coinbase/coinbase-wallet-sdk/assets/127766494/34b139d2-1730-41be-982c-41fbd7d5360b">

<img width="807" alt="image" src="https://github.com/coinbase/coinbase-wallet-sdk/assets/127766494/ef5f9198-8489-426f-b42a-bfa69fdac627">

### Expected behavior

On CoinbaseWalletSDK.js file;

line:13
from: const LINK_API_URL = process.env.LINK_API_URL || "https://www.walletlink.org";
to: const LINK_API_URL = process?.env.LINK_API_URL || "https://www.walletlink.org";

line:14
from: const SDK_VERSION = process.env.SDK_VERSION || require("../package.json").version || "unknown";
to: const SDK_VERSION = process?.env.SDK_VERSION || require("../package.json").version || "unknown";

and solved problem.

### Version

3.7.1

### Desktop

- Browser: Chrome, Firefox, Opeera

**Comment by scotthconner** [comment] 2023-08-08 20:27
Running into this issue too. I really don't want to custom patch the dependencies.

**Comment by VladimirMikulic** [comment] 2023-08-12 15:00
Duplicate of https://github.com/coinbase/coinbase-wallet-sdk/issues/874
The fix will be released in a new version.

**Comment by bangtoven** [comment] 2023-08-21 21:35
thanks. https://github.com/coinbase/coinbase-wallet-sdk/pull/953

**Closed by bangtoven** 2023-08-21 21:35 UTC
Labels: type: bug

**Comment by philcockfield** [comment] 2023-08-25 03:45
Thanks everyone for resolving this. 

Now the issue is closed, when should we expect it to come out in a release (bunch of downstream things breaking on this, as you know)

Thanks!
