### ISSUE TITLE
Bug: reloadOnDisconnect not working after a page reload

### ISSUE THREAD

**Issue by clayallsopp** [coinbase/coinbase-wallet-sdk#665] opened 2022-09-17 04:38 UTC
### Describe the bug

After connecting, then reloading the page, then disconnecting, the entire page reloads

### Steps

1. Go to https://app.uniswap.org/#/swap
2. Connect via Coinbase Wallet
3. Reload the page (cmd + R etc)
4. Disconnect via Uniswap's UI/disconnect button (click the address -> "Disconnect")
5. The page reloads, disregarding the internal `reloadOnDisconnect: false` setting. Via the network inspector, the initiator is the Coinbase Wallet extension (not the client-side JS) performing a `ui.reloadUI()`.

This _only_ happens after a full page reload is manually completed. If you connect -> disconnect, without manually reloading the page, there is no page reload (correctly respecting the `reloadOnDisconnect: false` setting).

### Expected behavior

The page should not do any reloads / always respect `reloadOnDisconnect: false`

### Version

3.5.0

### Additional info

Screenshot showing that the extension is reloading the UI:

<img width="1395" alt="Screen Shot 2022-09-17 at 12 37 04 AM" src="https://user-images.githubusercontent.com/153704/190840615-eda1426d-362b-42eb-b3f6-1d9d5039edc9.png">

### Desktop

- OS: Mac OS X
- Browser: Chrome

**Comment by Vladisvob** [comment] 2022-09-25 14:21
Duplicate of # #376

**Comment by saadqayyum-cyber** [comment] 2022-10-22 19:56
Facing Same Issue

**Comment by bangtoven** [comment] 2023-01-11 00:39
hi. sorry for the belated response. 
we have similar issues reported, so consolidating them into one for proper tracking.
https://github.com/coinbase/coinbase-wallet-sdk/issues/764

**Closed by bangtoven** 2023-01-11 00:39 UTC
Labels: type: bug, state: duplicate
