### ISSUE TITLE
"Error: Unknown Ethereum address" on transactions on L2 networks (Optimism)

### ISSUE THREAD

**Issue by earthtojake** [coinbase/coinbase-wallet-sdk#303] opened 2022-02-02 21:04 UTC
Unable to send transactions via WalletLink on Optimism with chainId 10. This might also be a WalletConnect issue for L2s specifically.

```
Error: Unknown Ethereum address
    at WalletLinkProvider._ensureKnownAddress (WalletLinkProvider.js?94ef:492:1)
    at WalletLinkProvider._prepareTransactionParams (WalletLinkProvider.js?94ef:502:1)
    at WalletLinkProvider._eth_sendTransaction (WalletLinkProvider.js?94ef:647:1)
    at WalletLinkProvider._handleAsynchronousMethods (WalletLinkProvider.js?94ef:437:1)
    at eval (WalletLinkProvider.js?94ef:392:1)
    at new Promise (<anonymous>)
    at WalletLinkProvider._sendRequestAsync (WalletLinkProvider.js?94ef:360:1)
    at WalletLinkProvider.request (WalletLinkProvider.js?94ef:296:1)
    at Web3Provider.eval [as jsonRpcFetchFunc] (web3-provider.js?b3d1:65:1)
    at Web3Provider.send (web3-provider.js?b3d1:129:1)
    at eval (json-rpc-provider.js?9643:186:1)
```

Transactions are going through for other connectors using web3-react (MetaMask, WalletConnect)

Related issue which was closed months ago and patched in web3-react v6: https://github.com/walletlink/coinbase-wallet-sdk/issues/149

**Comment by earthtojake** [comment] 2022-02-02 21:04
@brendanww reopened this to track the issue

**Comment by earthtojake** [comment] 2022-02-02 21:13
I've successfully executed transactions on mainnet with the latest version, it's Optimism transactions that are consistently failing for me.

Other dapps like uniswap and 1inch on Optimism also don't work.

**Comment by brendanww** [comment] 2022-02-02 21:15
@earthtojake can you clarify if you are using the standalone extension, extension paired w/ ios, extension paired w/ android, android, or ios when testing?

**Comment by earthtojake** [comment] 2022-02-02 21:32
ios for testing, haven't tested the extension yet, I will do that shortly

**Comment by earthtojake** [comment] 2022-02-02 21:33
I also tried clearing browser cache + local storage per the other issue thread but that didn't help

**Comment by brendanww** [comment] 2022-02-02 22:51
@earthtojake You can see app version by going to settings and scrolling down to the `About Coinbase Wallet` section. Can you confirm what iOS app version you are on?

**Comment by earthtojake** [comment] 2022-02-02 23:36
Version 25.7.552

**Comment by brendanww** [comment] 2022-02-02 23:42
@earthtojake I am trying to reproduce the issue but am unable to. If you're able to, it'd help if you could put a breakpoint in the chrome debugger on the first line of `_prepareTransactionParams` and share what the following values are at that breakpoint:

- `tx.from`
- `this.selectedAddress`
- `this._addresses`

as well as a breakpoint on the first line of `_ensureKnownAddress` and share what value you observe for local var `addressString`.

The last time this popped up it was an issue with comparison failing due to lowercase vs uppercase. I don't see any changes that should introduce that type of regression, but can rule that out based on what values you observe.

**Comment by earthtojake** [comment] 2022-02-05 03:00
@brendanww here are the values:

```
tx.from = "0x3ee80098615229a39920212171af51e67103f83b"
this.selectedAddress = "0x3EE80098615229A39920212171af51e67103f83B"
this._addresses = [
    "0x3EE80098615229A39920212171af51e67103f83B"
]
```

So looks like the address is being lowercased incorrectly.

**Comment by earthtojake** [comment] 2022-02-05 03:07
I'm getting the same error on the coinbase wallet chrome extension, and I've confirmed that web3-react is using `^2.4.5` version of walletlink, so I think this is a regression for Optimism (and maybe other non-mainnet networks)

**Comment by earthtojake** [comment] 2022-02-07 22:08
@brendanww looks like a fix to this is almost out, when should I expect it to be released?

**Comment by earthtojake** [comment] 2022-02-08 00:45
Merged in but I can't install 2.4.7

**Comment by brendanww** [comment] 2022-02-08 05:20
@earthtojake we will publish 2.6.7 tomorrow morning

**Comment by JamesSanderslawnmasters** [comment] 2022-02-08 17:43
IA a idiot on computers but do I have money in here

**Comment by earthtojake** [comment] 2022-02-09 00:28
Hi @brendanww this issue is resolved on the ios mobile app but we're still getting it on the desktop extension - any ideas?

**Comment by brendanww** [comment] 2022-02-09 03:24
@earthtojake if you are testing against your own dapp and updated to the latest walletlink, then that makes sense. the desktop extension injects its own version of walletlink into `window.ethereum` so the bug won't be fixed until we do a new extension release, which should be within a week.

**Closed** 2022-07-18 17:47 UTC
Labels: type: bug
