### ISSUE TITLE
Bug: missing reloadOnDisconnect option passed in to WalletSDKRelay

### ISSUE THREAD

**Issue by tindt-blockpass** [coinbase/coinbase-wallet-sdk#764] opened 2022-12-27 07:56 UTC
### Describe the bug

I need to disable reload on disconnect behavior, so I set it to false in my code, but it didn't not work at all.

### Steps

1. Connect to wallet.
2. Do some stuff (sign message).
3. Disconnect wallet.
=> The page auto reload even I set reloadOnDisconnect to false.

### Expected behavior

=> The page should not reload.

### Version

3.6.2

### Desktop

- OS: macOS Ventura 13.1
- Browser: Chrome and Safari.

**Comment by Helpcenter101** [comment] 2022-12-31 05:19
Hey @tindt-blockpass We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by taycaldwell** [comment] 2023-01-04 18:55
Cannot reproduce this behavior.

Do you have a demo/example where this behavior occurs?

Working demo: https://codesandbox.io/s/complete-uw25vs

```javascript
  const coinbaseWallet = new CoinbaseWalletSDK({
    appName: APP_NAME,
    appLogoUrl: APP_LOGO_URL,
    reloadOnDisconnect: false
  });
  ```

**Comment by afmfe-iul** [comment] 2023-01-06 00:37
@taycaldwell your example works, but I've added an example where the issue is happening, since no wallet is found (none is connected, you might have to disconnect yours from codesandbox), calling disconnect refreshes the page.

**Comment by bangtoven** [comment] 2023-01-11 00:41
we have similar issues reported, so consolidating them into one for proper tracking. cc @vishnumad 🙏

**Comment by toteto** [comment] 2023-01-17 14:20
Added related issue (https://github.com/coinbase/coinbase-wallet-sdk/issues/802) to keep on mind when fixing this bug. Without it the DApp will continue thinking it is connected.

**Comment by vishnumad** [comment] 2023-01-25 22:39
Fixed in https://github.com/coinbase/coinbase-wallet-sdk/pull/574

**Closed by vishnumad** 2023-01-25 22:39 UTC
Labels: type: bug, state: duplicate
